### ISSUE TITLE
can't make it work on osx 0.9.8

### ISSUE THREAD

**Issue by moebiussurfing** [kritzikratzi/ofxMightyUI#3]
I am stuck with this error; file not found
#include "MUI.h"

**Comment by EmersonSnow** [comment]
I've used
#include "ofxMightyUI.h"

I've not tested it yet, I think the author changed it to openFrameworks naming convention. However, I'm struggling with the lack of examples, so I might look for an alternative!

**Comment by moebiussurfing** [comment]
thanks. not working. now I am getting fontstash2 errors
ofximgui seems the people choice lately or ofxdatgui if you want more cooler look

**Comment by kritzikratzi** [comment]
yes, example project file is outdated (changing MUI.h to ofxMightyUI.h is definitely right, you should also just delete the example project file and refresh it with the PG). 

if you decide to spend more time, PRs for examples/documentation are very welcome.

**Comment by kritzikratzi** [comment]
closing this, because of.98 is also outdated now :) current work is happening in the of10 branch which is already fully working and will be merged into master eventually.
